<a href="https://colab.research.google.com/github/B-SatheesKumar/Machine_Learning/blob/main/numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.random.seed(42)
data = np.random.rand(5, 5)

In [ ]:
# 1. Display the dataset
print("Original Dataset:")
print(data)
print("\n")

Original Dataset:
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]]




In [ ]:
# 2. Get the shape of the dataset
print("Shape of the dataset:")
print(data.shape)
print("\n")

Shape of the dataset:
(5, 5)




In [ ]:
# 3. Reshape the dataset
reshaped_data = data.reshape((1, 25))
print("Reshaped Dataset:")
print(reshaped_data)
print("\n")

Reshaped Dataset:
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
  0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985
  0.83244264 0.21233911 0.18182497 0.18340451 0.30424224 0.52475643
  0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184
  0.45606998]]




In [ ]:
# 4. Transpose the dataset
transposed_data = data.T
print("Transposed Dataset:")
print(transposed_data)
print("\n")

Transposed Dataset:
[[0.37454012 0.15599452 0.02058449 0.18340451 0.61185289]
 [0.95071431 0.05808361 0.96990985 0.30424224 0.13949386]
 [0.73199394 0.86617615 0.83244264 0.52475643 0.29214465]
 [0.59865848 0.60111501 0.21233911 0.43194502 0.36636184]
 [0.15601864 0.70807258 0.18182497 0.29122914 0.45606998]]




In [ ]:
# 5. Slice a portion of the dataset
sliced_data = data[:2, :2]
print("Sliced Dataset:")
print(sliced_data)
print("\n")

Sliced Dataset:
[[0.37454012 0.95071431]
 [0.15599452 0.05808361]]




In [ ]:
# 6. Compute the mean along a specific axis
mean_axis_0 = np.mean(data, axis=0)
print("Mean along axis 0:")
print(mean_axis_0)
print("\n")

Mean along axis 0:
[0.26927531 0.48448877 0.64950276 0.44208389 0.35864306]




In [ ]:
# 7. Compute the sum along a specific axis
sum_axis_1 = np.sum(data, axis=1)
print("Sum along axis 1:")
print(sum_axis_1)
print("\n")

Sum along axis 1:
[2.81192549 2.38944187 2.21710107 1.73557734 1.86592323]




In [ ]:
# 8. Element-wise addition
addition_result = data + 1
print("Element-wise Addition:")
print(addition_result)
print("\n")

Element-wise Addition:
[[1.37454012 1.95071431 1.73199394 1.59865848 1.15601864]
 [1.15599452 1.05808361 1.86617615 1.60111501 1.70807258]
 [1.02058449 1.96990985 1.83244264 1.21233911 1.18182497]
 [1.18340451 1.30424224 1.52475643 1.43194502 1.29122914]
 [1.61185289 1.13949386 1.29214465 1.36636184 1.45606998]]




In [ ]:
# 9. Element-wise multiplication
multiplication_result = data * 2
print("Element-wise Multiplication:")
print(multiplication_result)
print("\n")

Element-wise Multiplication:
[[0.74908024 1.90142861 1.46398788 1.19731697 0.31203728]
 [0.31198904 0.11616722 1.73235229 1.20223002 1.41614516]
 [0.04116899 1.9398197  1.66488528 0.42467822 0.36364993]
 [0.36680902 0.60848449 1.04951286 0.86389004 0.58245828]
 [1.22370579 0.27898772 0.5842893  0.73272369 0.91213997]]




In [ ]:
# 10. Matrix multiplication
matrix_product = np.dot(data, data.T)
print("Matrix Multiplication:")
print(matrix_product)
print("\n")

Matrix Multiplication:
[[1.96268692 1.21801794 1.69464656 1.04608305 0.86611142]
 [1.21801794 1.64067514 1.03697439 0.96667309 0.89975298]
 [1.69464656 1.03697439 1.71225781 0.88036402 0.55180267]
 [1.04608305 0.96667309 0.88036402 0.67296078 0.59903033]
 [0.86611142 0.89975298 0.55180267 0.59903033 0.82139183]]




In [ ]:
# 11. Compute the element-wise square root
sqrt_result = np.sqrt(data)
print("Element-wise Square Root:")
print(sqrt_result)
print("\n")

Element-wise Square Root:
[[0.61199683 0.9750458  0.85556645 0.77373024 0.39499195]
 [0.39496142 0.24100542 0.93068585 0.77531607 0.84147049]
 [0.14347297 0.98484001 0.91238295 0.46080268 0.42640939]
 [0.42825753 0.55158158 0.72440074 0.65722524 0.5396565 ]
 [0.78221026 0.37348877 0.54050407 0.60527832 0.67532954]]




In [ ]:
# 12. Compute the element-wise exponential
exp_result = np.exp(data)
print("Element-wise Exponential:")
print(exp_result)
print("\n")

Element-wise Exponential:
[[1.45432245 2.58755731 2.07922233 1.81967604 1.16884799]
 [1.1688198  1.0598036  2.37780108 1.82415162 2.03007467]
 [1.02079782 2.63770667 2.29892734 1.23656715 1.19940424]
 [1.20130025 1.3555974  1.69004716 1.54025043 1.33807115]
 [1.84384469 1.14969175 1.33929673 1.4424771  1.57786077]]




In [ ]:
# 13. Compute the element-wise natural logarithm
log_result = np.log(data)
print("Element-wise Natural Logarithm:")
print(log_result)
print("\n")

Element-wise Natural Logarithm:
[[-0.98205636 -0.05054168 -0.31198304 -0.51306399 -1.85777979]
 [-1.8579344  -2.84587172 -0.14366699 -0.508969   -0.34520868]
 [-3.88321719 -0.03055215 -0.18339096 -1.5495707  -1.70471077]
 [-1.69606113 -1.18993104 -0.64482106 -0.83945697 -1.2336449 ]
 [-0.49126339 -1.96973469 -1.23050623 -1.00413379 -0.78510901]]




In [ ]:
# 14. Concatenate two arrays along a specified axis
concatenated_data = np.concatenate((data, data), axis=1)
print("Concatenated Dataset:")
print(concatenated_data)
print("\n")

Concatenated Dataset:
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.37454012
  0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258 0.15599452
  0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497 0.02058449
  0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914 0.18340451
  0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998 0.61185289
  0.13949386 0.29214465 0.36636184 0.45606998]]




In [ ]:
# 15. Find the unique elements in the dataset
unique_elements = np.unique(data)
print("Unique Elements:")
print(unique_elements)
print("\n")

Unique Elements:
[0.02058449 0.05808361 0.13949386 0.15599452 0.15601864 0.18182497
 0.18340451 0.21233911 0.29122914 0.29214465 0.30424224 0.36636184
 0.37454012 0.43194502 0.45606998 0.52475643 0.59865848 0.60111501
 0.61185289 0.70807258 0.73199394 0.83244264 0.86617615 0.95071431
 0.96990985]




In [ ]:
# 16. Compute the dot product of two vectors
vector_1 = np.array([1, 2, 3])
vector_2 = np.array([4, 5, 6])
dot_product = np.dot(vector_1, vector_2)
print("Dot Product of Vectors:")
print(dot_product)
print("\n")

Dot Product of Vectors:
32




In [ ]:
# 17. Compute the cross product of two vectors
cross_product = np.cross(vector_1, vector_2)
print("Cross Product of Vectors:")
print(cross_product)
print("\n")

Cross Product of Vectors:
[-3  6 -3]




In [ ]:
# 18. Compute the cumulative sum along a specified axis
cumulative_sum_axis_0 = np.cumsum(data, axis=0)
print("Cumulative Sum along axis 0:")
print(cumulative_sum_axis_0)
print("\n")

Cumulative Sum along axis 0:
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.53053464 1.00879792 1.59817009 1.1997735  0.86409122]
 [0.55111913 1.97870777 2.43061273 1.41211261 1.04591619]
 [0.73452364 2.28295001 2.95536916 1.84405763 1.33714533]
 [1.34637654 2.42244387 3.24751381 2.21041947 1.79321531]]




In [ ]:
# 19. Generate a random integer array
random_integers = np.random.randint(0, 10, size=(3, 3))
print("Random Integer Array:")
print(random_integers)
print("\n")

Random Integer Array:
[[2 6 3]
 [8 2 4]
 [2 6 4]]




In [ ]:
# 20. Compute the mean absolute deviation
mad_result = np.mean(np.abs(data - np.mean(data)))
print("Mean Absolute Deviation:")
print(mad_result)
print("\n")

Mean Absolute Deviation:
0.24023807292329138


